# Generated by Django 5.2.1 on 2026-05-27 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaJoiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('hirer', 'Hirer'), ('company', 'Company')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('github_username', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=180)),
                ('primary_stack', models.CharField(blank=True, max_length=180)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('interviewing', 'Interviewing'), ('busy', 'Busy')], default='available', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('code_score', models.PositiveSmallIntegerField(default=0)),
                ('repositories_count', models.PositiveIntegerField(default=0)),
                ('commits_count', models.PositiveIntegerField(default=0)),
                ('open_source_contributions', models.PositiveIntegerField(default=0)),
                ('last_github_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-code_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HirerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=180)),
                ('company_website', models.URLField(blank=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=20)),
                ('hiring_needs', models.TextField(blank=True)),
                ('active_jobs_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_score', models.PositiveSmallIntegerField(default=0)),
                ('repositories_count', models.PositiveIntegerField(default=0)),
                ('commits_count', models.PositiveIntegerField(default=0)),
                ('open_source_contributions', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='DeveloperHieringHub.developerprofile')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_repo_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=180)),
                ('full_name', models.CharField(max_length=260)),
                ('url', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=80)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('commits_count', models.PositiveIntegerField(default=0)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='DeveloperHieringHub.developerprofile')),
            ],
            options={
                'ordering': ['-stars', 'name'],
                'unique_together': {('developer', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha', models.CharField(max_length=80, unique=True)),
                ('message', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('committed_at', models.DateTimeField()),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='DeveloperHieringHub.developerprofile')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='DeveloperHieringHub.githubrepository')),
            ],
            options={
                'ordering': ['-committed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('company_name', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('contract', 'Contract'), ('part_time', 'Part-time'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('required_skills', models.CharField(blank=True, max_length=260)),
                ('is_active', models.BooleanField(default=True)),
                ('hirer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='DeveloperHieringHub.hirerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('hirer', 'Hirer'), ('admin', 'Admin')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('avatar_url', models.URLField(blank=True)),
                ('github_username', models.CharField(blank=True, max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhh_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='hirerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hirer_profile', to='DeveloperHieringHub.platformuser'),
        ),
        migrations.CreateModel(
            name='GitHubAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_user_id', models.CharField(blank=True, max_length=80)),
                ('username', models.CharField(max_length=120)),
                ('access_token_reference', models.CharField(blank=True, max_length=255)),
                ('scopes', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_auth', to='DeveloperHieringHub.platformuser')),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to='DeveloperHieringHub.platformuser'),
        ),
        migrations.CreateModel(
            name='DeveloperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('years_used', models.PositiveSmallIntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeveloperHieringHub.developerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeveloperHieringHub.skill')),
            ],
            options={
                'ordering': ['skill__name'],
                'unique_together': {('developer', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, through='DeveloperHieringHub.DeveloperSkill', to='DeveloperHieringHub.skill'),
        ),
    ]
