# Generated by Django 6.0.5 on 2026-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeveloperHieringHub', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
